@startuml
'!include ./style.iuml
!pragma teoz true
title Medication Product Info   \t- \tActor Diagram\n
skinparam linetype polyline


rectangle "Product Data Provider" {
  agent "  [[actors_and_transactions.html#product-data-provider Product Data \nProvider (Regulatory)]]" as proddataprovider
  agent "  [[actors_and_transactions.html#product-data-provider Product Data \nProvider (Clinical) ]]" as proddataproviderc
}

rectangle "Product Data Consumer" {
agent " [[actors_and_transactions.html#product-data-consumer Product Data \nConsumer (Regulatory) ]]" as proddataconsumer
agent " [[actors_and_transactions.html#product-data-consumer Product Data \nConsumer (Clinical) ]]" as proddataconsumerc
}

agent "**[[actors_and_transactions.html#substitution-adviser Substitution Adviser]]**" as substadviser
agent "**[[actors_and_transactions.html#substitution-requester Substitution Requester]]**" as substrequester



proddataprovider -- proddataconsumer : " **↓**  [[u3.html Submit regulatory\nproduct data \nPHARM-U3 ]]       \n\n\n\n **↑**  [[u1.html Query regulatory\nproduct data\nPHARM-U1]]       "

proddataproviderc -- proddataconsumerc : " **↓**  [[u4.html Submit clinical\nproduct data \nPHARM-U4 ]]    \n\n\n\n **↑**  [[u2.html Query clinical\nproduct data\nPHARM-U2]]   "

proddataprovider -[hidden]r- proddataproviderc : "                 "

proddataconsumer -[hidden]r- proddataconsumerc : "              "


proddataproviderc -[hidden]r- substadviser : "\t\t"
substadviser -d- substrequester : " [[u5.html PHARM-U5 \nQuery for Substitutes]] ↑   "
@enduml
