@startuml
hide footbox
participant "[[actors_and_transactions.html#product-data-provider Product Data\nProvider]]" as a1
participant "[[actors_and_transactions.html#product-data-consumer Product Data\nConsumer ]]" as a2

a1 -> a2 : [[u1.html PHARM-U1]]\n Submit product data
activate a1
activate a2

@enduml