# sushi-config.yaml is documented https://fshschool.org/docs/sushi/configuration/
# ───────────────────────────────────────────────────
# the id should be lowercase made up of "ihe." + {domain acronym} + "." + {profile acronym/short-name}
# e.g. ihe.iti.mhds, or ihe.iti.basicaudit
id: ihe.pharm.unicom.transactions
canonical: https://profiles.ihe.net/Pharm/unicom-transactions
version: 0.0.1
name: IHEUnicomTransactions
title: "IHE UNICOM Transactions"
description: IHE transactions for the UNICOM project
releaseLabel: ci-build
#releaseLabel: Trial-Implementation
#date: 2022-01-02
status: active
publisher:
  - name: UNICOM
  - url: https://unicom-project-eu
  - email: unicom@example.com
contact:
  - name: UNICOM
    telecom:
      - system: email
        value: iti@ihe.net
license:  CC-BY-4.0
fhirVersion: 5.0.0
jurisdiction: 'http://unstats.un.org/unsd/methods/m49/m49.htm#001'
#copyright: IHE http://www.ihe.net/Governance/#Intellectual_Property
copyrightYear: 2023+


parameters:  # see https://confluence.hl7.org/display/FHIR/Implementation+Guide+Parameters
  path-resource:
    - input/resources
    - fsh-generated/resources
    - input/examples
#  path-pages:
#    - input/pagecontent
#    - fsh-generated/includes
  show-inherited-invariants: 'false'
  usage-stats-opt-out: 'false'
  logging: progress
  shownav: 'true'
  active-tables: 'false'
  apply-contact: 'true'
  apply-jurisdiction: 'true'
  apply-publisher: 'true'
  apply-version: 'true'

resources:
# list every example here with a name, description and that exampleBoolean is true; These are used to populate the artifacts page, and are needed to eliminate build warnings 
# You may delay filling out this section until you approach publication as it is merely a nice to have and eliminates build warnings -- If you do this then you will need above the autoload-resources true


pages:
# itemize here each narrative page. Include assigned section numbers when appropriate
  index.md:
    title: 1. Home
    generation: markdown
  volume-1.html:
    title: Volume 1
    generation: markdown
    requirements.html:
      title: Requirements
      generation: markdown
    actors_and_transactions:
      title: Actors and Transactions
      generation: markdown
    
  volume-2.html:
    title: Volume 2
    generation: markdown

  # t1-createfullproduct.md:
  #   title: Transaction 1 - Create Full Product
  #   generation: markdown
  # volume-1.md:
  #   title: 1:XX. Profile Volume 1
  #   generation: markdown
  # testplan.md:
  #   title: "Test Plan"
  #   generation: markdown
    
menu:
  Home: index.html
  Volume 1:
    Introduction: volume-1.html
    Requirements: requirements.html
    Actors and Transactions: volume-1.html#actors-and-transactions
    Actor Options: volume-1.html#actor-options
#     Required Groupings: volume-1.html#required-groupings
#     Overview: volume-1.html#overview
#     Security Considerations: volume-1.html#security-considerations
#     Cross-Profile Considerations: volume-1.html#other-grouping
#   Volume 2:
#     "Transaction one [Domain-YY]": domain-YY.html
#   Test Plan: testplan.html
#   Artifacts: artifacts.html
#   Other: other.html

dependencies:
  hl7.eu.fhir.unicom: current
